config/routes.rb
Rails.application.routes.draw do

      resources :enterprises
      root to: 'home#index'
      get '/home', to: 'home#index'
      get '/category_enterprise/:id' => 'enterprises#show_categories'
      post '/signup_user' => 'users#create'
      post '/signin_user' => 'users#login'
      get '/get_user_preference/:id' => 'users#get_user_preference'
      put '/update' => 'users#update'
      put '/update_preferences' => 'users#update_preferences'
      post '/user_phones' => 'users#checkusers'
      post '/users/follow_provider' => 'users#follow_provider'
      post '/users/unfollow_provider' => 'users#unfollow_provider'
      get '/users/enterprises/:id_user' => 'users#show_providers_by_user'
      post '/search_enterprises' => 'enterprises#search_enterprise'
      post '/evaluate_provider' => 'rating#create'
      post '/users/profile_picture' => 'users#save_profile_picture'
      get '/enterprises_best_rated/:id_category' => 'enterprises#search_ranking_enterprises'
      post '/users/advise_provider' => 'users#advise_provider'
      get '/users/enterprises_advised/:id_user' => 'users#show_providers_advised_by_user'
      get '/enterprise/messages/:id_enterprise' => 'recomendation_message#show'
      post '/enterprise/create_recomendation' => 'recomendation_message#create'
      get '/login' => 'sessions#new'
      post '/login' => 'sessions#create'
      get '/logout' => 'sessions#destroy'
      put '/update_picture' => 'enterprises#pick_image'

      get '/near_enterprises' => 'enterprises#get_near_enterprises'

      resources :enterprises
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  #before_save :verify_email
  has_many :ratings
  has_many :pictures

  #REVIEW: to consert the auto-association to be
  # 		bilateral.
  has_many :friends, class_name: "User"
  					#foreign_key: "friend_"
  belongs_to :user

  has_many :preferences
  has_many :categories, through: :preferences

  has_many :advises
  has_many :enterprises, through: :advises

  has_and_belongs_to_many :enterprises, :uniq => true

  after_create :populate_user_with_preference

  after_create :populate_user_with_preference

  validates :email, uniqueness: true

  def populate_user_with_preference
  	# @user = User.create name: "Jonas",
  	# 					password: "123",
  	# 					password_confirmation: "123"

  	preference1 = Preference.create  budget: 100,
  							user_id: self.id,
  							category_id: Category.find(1).id

  	preference2 = Preference.create budget: 200,
  							user_id: self.id,
  							category_id: Category.find(2).id

  	preference3 = Preference.create budget: 400,
  							user_id: self.id,
  							category_id: Category.find(3).id

  	preference4 = Preference.create budget: 500,
  							user_id: self.id,
  							category_id: Category.find(4).id

  	preference5 = Preference.create budget: 600,
  							user_id: self.id,
  							category_id: Category.find(5).id,
                musician: true,
                band: true,
                dj: false

  	preference6 = Preference.create budget: "600",
  							user_id: self.id,
  							category_id: Category.find(6).id
  end

end

app/controllers/enterprises_controller.rb
class EnterprisesController < ApplicationController
  before_action :set_enterprise, only: [:show, :edit, :update, :destroy]
  before_action :authorize, only: [:edit, :update, :destroy]

  # GET /enterprises
  # GET /enterprises.json
  def index
    #@enterprises = Enterprise.all
    @enterprise = Enterprise.find current_enterprise.id
    @categories_of_enterprise = @enterprise.categories.uniq
    @categories = Category.all
    @pictures = Picture.find_by_enterprise_id(current_enterprise.id)
    @picture = Picture.new
    #@picture = Picture.new enterprise_id: current_enterprise.id,
                            #category_id:
  end

  # GET /enterprises/1
  # GET /enterprises/1.json
  def show
  end

  def pick_image
    @picture = Picture.new    enterprise_id: current_enterprise.id,
                              category_id: params[:category],
                              picture: params[:cover]

    # render json: picture.json
    if @picture.save
      redirect_to action: :index
    end
  end

  # GET /enterprises/new
  def new
    @enterprise = Enterprise.new
    @categories = Category.all
  end

  # GET /enterprises/1/edit
  def edit
    @enterprise = Enterprise.find(current_enterprise.id)
    @categories = Category.all
  end

  # POST /enterprises
  # POST /enterprises.json
  def create
    @enterprise = Enterprise.new(enterprise_params)

    respond_to do |format|
      if @enterprise.save
        session[:enterprise_id] = @enterprise.id
        format.html { redirect_to '/enterprises', notice: 'Enterprise was successfully created.' }
        format.json { render :show, status: :created, location: @enterprise }
      else
        format.html { render :new }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /enterprises/1
  # PATCH/PUT /enterprises/1.json
  def update
    respond_to do |format|
      if @enterprise.update(enterprise_params)
        format.html { redirect_to '/enterprise', notice: 'Enterprise was successfully updated.' }
        format.json { render :show, status: :ok, location: @enterprise }
      else
        format.html { render :edit }
        format.json { render json: @enterprise.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /enterprises/1
  # DELETE /enterprises/1.json
  def destroy
    @enterprise.destroy
    respond_to do |format|
      format.html { redirect_to enterprises_url, notice: 'Enterprise was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def show_categories
		@category = Category.find(params[:id])
    @enterprises = @category.enterprises.limit(10).offset(params[:offset])
    render :json => @enterprises.to_json(include: :pictures)
	end

	def search_enterprise
		if params[:search]
	      @enterprise = Category.find(params[:id]).enterprises.search(params[:search])
	      render :json => @enterprise.to_json(include: :pictures)
	    else
	      @category = Category.find(params[:id])
	      render :json => @category.enterprises.to_json(include: :pictures)
	    end
	end

	def search_ranking_enterprises
		@user = User.find(params[:id_user])
		budget = @user.preferences.find_by_category_id(params[:id_category]).budget
		@enterprises = Category.find(params[:id_category]).enterprises.order(:rate).where("base_price <= ?", budget).reverse
		render :json => @enterprises.to_json(include: :pictures)
	end

  def get_near_enterprises
    @near_enterprises = Enterprise.near(40.6898869,  -74.0446704, 30, units: :km)
    render :json => @near_enterprises.to_json
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_enterprise
      @enterprise = Enterprise.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def enterprise_params
      params.require(:enterprise).permit(:name, :description, :capacity, :telephone, :cellphone, :base_price,
       :address, :email, :password, :password_confirmation, :latitude, :longitude,:category_ids => [])
    end

    def category_params
  		params.require(:category).permit(:name)
  	end

    def picture_params
      params.permit(:cover, :category, :picture)
    end
end

app/helpers/enterprises_helper.rb
module EnterprisesHelper
end

app/views/enterprises/_button_settings.html.erb
<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
   <a class="btn-floating btn-large red">
     <i class="large material-icons">mode_edit</i>
   </a>
   <ul>
     <li><a href='/logout' class="btn-floating red"><i class="material-icons">settings_power</i></a></li>
     <li><a class="btn-floating yellow darken-1"><i class="material-icons">insert_chart</i></a></li>
     <li><a href='/enterprises' class="btn-floating green"><i class="material-icons">publish</i></a></li>
     <li><a href='/enterprises/<%= current_enterprise.id %>/edit' class="btn-floating blue"><i class="material-icons">perm_identity</i></a></li>
   </ul>
 </div>

app/views/enterprises/_form.html.erb
  <%= form_for(@enterprise) do |f| %>
    <% if @enterprise.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@enterprise.errors.count, "error") %> prohibited this enterprise from being saved:</h2>

        <ul>
        <% @enterprise.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class='row'>
    <div class="input-field col s12">
      <%= f.label :name %>
      <%= f.text_field :name, size:20, class: "validate" %>
    </div>
  </div>
  <div class='row'>
    <div class="input-field col s12">
      <%= f.label :description %>
      <%= f.text_field :description %>
    </div>
  </div>
  <div class='row'>
    <div class="input-field col s6">
      <%= f.label :capacity %>
      <%= f.number_field :capacity %>
    </div>
    <div class="input-field col s6">
      <%= f.label :base_price %>
      <%= f.text_field :base_price %>
    </div>
  </div>
  <div class='row'>
    <div class="input-field col s6">
      <%= f.label :telephone %>
      <%= f.telephone_field :telephone %>
    </div>
    <div class="input-field col s6">
      <%= f.label :cellphone %>
      <%= f.telephone_field :cellphone %>
    </div>
  </div>
  <div class='row'>
    <div class="input-field col s12">
      <%= f.label :email %>
      <%= f.email_field :email %>
    </div>
  </div>
  <div class='row'>
    <div class="input-field col s6">
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class="input-field col s6">
      <%= f.label :password_confirmation %>
      <%= f.password_field :password_confirmation %>
    </div>
  </div>
  <div class='row'>
    <div class="input-field col s12">
      <%= f.label :address %>
      <%= f.text_field :address %>
    </div>
  </div>
  <div class='row'>
    <div class="col s6">
      <%= f.label 'Categorias da sua empresa' %>
      <%= collection_check_boxes(:enterprise, :category_ids, @categories, :id, :name) do |b| %>
      <div>
        <%= b.check_box %>
        <%= b.label %>
      </div>
      <% end %>
    </div>
  </div>
    <% if false %>
    <div>
      <%= fields_for :category do |c| %>
        <% @categories.each do |a| %>
        <div>
          <%= c.check_box a.name, {class: 'filled-in'}, "yes", "no" %>
          <%= c.label a.name %>
        </div>
        <% end %>
      <% end %>
    </div>
    <% end %>
    <div class='row'>
    <div class="col s6 offset-s8">
      <%= f.submit 'Criar', class: "waves-effect waves-light btn" %>
    </div>
  </div>
  <% end %>

app/views/enterprises/edit.html.erb
<h1>Editing Enterprise</h1>

<%= render 'form' %>

<%= link_to 'Show', @enterprise %> |
<%= link_to 'Back', enterprises_path %>
<%= render 'button_settings' %>

app/views/enterprises/index.html.erb
<style>
.btn-file {
    position: relative;
    overflow: hidden;
}

.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}
</style>
<h3>Upload de arquivo</h3>
<!-- Form to upload image -->
<div class='container'>
  <div class='row'>
    <%= form_tag '/update_picture', method: :put, :enctype =>"multipart/form-data" do %>

      <div class='row'>
        <div class='col s12'>
          <span class='waves-effect waves-light btn btn-file'>
            Upload de imagem
              <%= file_field_tag :cover, accept: 'image/png,image/gif,image/jpeg'%>
          </span>
        </div>
      </div>

      <div class='row'>
        <div class='col s6'>
          <%= cl_image_tag("sample.jpg", :width => 200, :height => 250, :crop => :fill) %>
        </div>

      <div class='col s6'>
        <%= label_tag :category, 'categoria da imagem' %>
        <%= select_tag('category', options_from_collection_for_select(@categories_of_enterprise, "id", "name"), class: 'browser-default') %>
      </div>

      <div class='col s4'>
        <%= submit_tag 'enviar', class: 'btn waves-effect waves-light' %>
      </div>
      <% end %>
      <% if false %>
        <%= link_to 'New Enterprise', new_enterprise_path %>
        <%= link_to 'Logout', '/logout' %>
      <% end %>
    </div>
  </div>
</div>

<!-- options button -->
<div class="fixed-action-btn vertical" style="bottom: 45px; right: 24px;">
   <a class="btn-floating btn-large red">
     <i class="large material-icons">mode_edit</i>
   </a>
   <ul>
     <li><a href='/logout' class="btn-floating red"><i class="material-icons">settings_power</i></a></li>
     <li><a class="btn-floating yellow darken-1"><i class="material-icons">insert_chart</i></a></li>
     <li><a href='/enterprises' class="btn-floating green"><i class="material-icons">publish</i></a></li>
     <li><a href='/enterprises/<%= current_enterprise.id %>/edit' class="btn-floating blue"><i class="material-icons">perm_identity</i></a></li>
   </ul>
 </div>

app/views/enterprises/new.html.erb
<nav class="top-nav" style="background-color: rgba(12, 39, 70, 1.0)">
     <div class="nav-wrapper">
         <ul class="right">
            <li><a href="#" style="color: rgba(255, 255, 255, 1.0)">Login</a></li>
         </ul>
    </div>
</nav>
<br></br>
<div class="valign-wrapper container">
      <div class="col s10">
        <h5>Criar conta para minha empresa</h5>
      <%= render 'form' %>
      </div>

      <div class="valign row">
        <div class="col s6 offset-s5">
          <%= image_tag "iphone.png", style: 'height160%;width:160%;' %>
        </div>
      </div>
</div>



<footer class="page-footer" style="background-color: rgba(235, 117, 135, 1.0);">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Biografia</h5>
        <p class="grey-text text-lighten-4">Projeto desenvolvido por um time de estudantes do curso de Engenharia de Software da Universidade de Brasília para a diciplina de Desenvolvimento Avançado de Software</p>

      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Configurações</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
        </ul>
      </div>
      <div class="col l3 s12">
        <h5 class="white-text">Conecte-se</h5>
        <ul>
          <li><a class="white-text" href="#!">Link 1</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright" style="background-color: rgba(217, 67, 100, 1.0)">
  </div>
</footer>

app/views/enterprises/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @enterprise.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @enterprise.description %>
</p>

<p>
  <strong>Capacity:</strong>
  <%= @enterprise.capacity %>
</p>

<p>
  <strong>Telephone:</strong>
  <%= @enterprise.telephone %>
</p>

<p>
  <strong>Cellphone:</strong>
  <%= @enterprise.cellphone %>
</p>

<p>
  <strong>Base price:</strong>
  <%= @enterprise.base_price %>
</p>

<p>
  <strong>Email:</strong>
  <%= @enterprise.email %>
</p>

<p>
  <strong>Endereço:</strong>
  <%= @enterprise.address %>
</p>


<%= link_to 'Edit', edit_enterprise_path(@enterprise) %> |
<%= link_to 'Back', enterprises_path %>